name: 'Flake8'
description: 'Run Flake8'
inputs:
  directory-to-check:  # id of input
    description: 'Which directory to run flake8 in'
    required: true
    
runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: 'actions/setup-python@v1'
      with:
        python-version: 3.8
        architecture: x64
    - name: 'Install flake8'
      run: pip install flake8
    - name: 'Run flake8'
      uses: TrueBrain/actions-flake8@v2
      with:
        path: ${{ inputs.directory }}