name: 'Flake8'
description: 'Run Flake8'
inputs:
  directory:  # id of input
    description: 'Which directory to run flake8 in'
    required: true
    
runs:
  using: "composite"
  steps:
    - name: Setup Python
      working-directory: ${{ inputs.directory }}
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
        architecture: x64
    - name: Install flake8
      working-directory: ${{ inputs.directory }}
      run: pip install flake8
    - name: Run flake8
      working-directory: ${{ inputs.directory }}
      uses: suo/flake8-github-action@releases/v1
      with:
        checkName: 'flake8_py3'   # NOTE: this needs to be the same as the job name
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}