name: 'pytest'
description: 'Run pytest'
inputs:
  directory-to-check:  # id of input
    description: 'Which directory to run pytest in'
    required: true
    
runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: 'actions/setup-python@v2'
      with:
        python-version: '3.8'
        architecture: x64
        
    - name: 'Run pytest'
      run: pytest -m ${{ inputs.directory-to-check }}
      shell: bash