# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  lambda_packaging:
    name: "Lambda Packaging"
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        environment: ["Dev", "Prd"]
        include:
        - environment: "Dev"
          domain_owner_account_id: "1234"
        - environment: "Prd"
          domain_owner_account_id: "4567"
    steps:
      - name: ECHO OUTPUT
        run: echo "${{ matrix.environment }} ${{ matrix.domain_owner_account_id} }"
          
          
  # flake8_backend:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repo
  #       uses: actions/checkout@v2

  #     - name: Run flake8 for backend
  #       uses: ./.github/actions/flake8
  #       with:
  #         directory-to-check: 'backend'
  # pytest_backend:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repo
  #       uses: actions/checkout@v2

  #     - name: Run pytest for backend
  #       uses: ./.github/actions/pytest
  #       with:
  #         directory-to-check: 'backend'

  # flake8_containers:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repo
  #       uses: actions/checkout@v2

  #     - name: Run flake8 for backend
  #       uses: ./.github/actions/flake8
  #       with:
  #         directory-to-check: 'containers'
  # pytest_containers:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repo
  #       uses: actions/checkout@v2

  #     - name: Run pytest for backend
  #       uses: ./.github/actions/pytest
  #       with:
  #         directory-to-check: 'containers'

  # flake8_lambda:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repo
  #       uses: actions/checkout@v2

  #     - name: Run flake8 for backend
  #       uses: ./.github/actions/flake8
  #       with:
  #         directory-to-check: 'lambda'
  # pytest_lambda:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout repo
  #       uses: actions/checkout@v2

  #     - name: Run pytest for backend
  #       uses: ./.github/actions/pytest
  #       with:
  #         directory-to-check: 'lambda'


  # build_backend:
  #   runs-on: ubuntu-latest
  #   needs: [flake8_backend, pytest_backend]
  #   steps:
  #     - name: Build Backend
  #       run: echo 'Build Backend'
  # build_lambda:
  #   runs-on: ubuntu-latest
  #   needs: [flake8_lambda, pytest_lambda]
  #   steps:
  #     - name: Build Backend
  #       run: echo 'Build Backend'
  # build_containers:
  #   runs-on: ubuntu-latest
  #   needs: [flake8_containers, pytest_containers]
  #   steps:
  #     - name: Build Backend
  #       run: echo 'Build Backend'
